/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form.subform;

import Form.Dashboard;
import Methods.DatabaseManager;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Default
 */
public class PayrollReports extends javax.swing.JFrame {
  private DatabaseManager dbManager;
    java.sql.Connection con = null;
    Statement stmt = null;
    ResultSet rs = null; 
    
    public PayrollReports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 0));
        setMaximumSize(new java.awt.Dimension(900, 900));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(33, 35, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monthly Payroll Summary Report");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payslip Reports");

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(7, 4));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PayPeriod ID");
        jLabel12.setOpaque(true);
        jPanel2.add(jLabel12);

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Start Date");
        jLabel16.setOpaque(true);
        jPanel2.add(jLabel16);

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("End Date");
        jLabel17.setOpaque(true);
        jPanel2.add(jLabel17);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Action");
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("400001");
        jLabel49.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel49.setOpaque(true);
        jLabel49.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel49);

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("2022-09-01");
        jLabel50.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel50.setOpaque(true);
        jLabel50.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel50);

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("2022-09-15");
        jLabel48.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel48.setOpaque(true);
        jLabel48.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel48);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View");
        jLabel4.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);

        jLabel34.setBackground(new java.awt.Color(204, 204, 204));
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("400002");
        jLabel34.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel34.setOpaque(true);
        jLabel34.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel34);

        jLabel43.setBackground(new java.awt.Color(204, 204, 204));
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("2022-09-16");
        jLabel43.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel43.setOpaque(true);
        jLabel43.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel43);

        jLabel44.setBackground(new java.awt.Color(204, 204, 204));
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("2022-09-30");
        jLabel44.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel44.setOpaque(true);
        jLabel44.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel44);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("View");
        jLabel5.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("400003");
        jLabel45.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel45.setOpaque(true);
        jLabel45.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel45);

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setForeground(new java.awt.Color(51, 51, 51));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("2022-10-01");
        jLabel46.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel46.setOpaque(true);
        jLabel46.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel46);

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("2022-10-15");
        jLabel47.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel47.setOpaque(true);
        jLabel47.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel47);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("View");
        jLabel6.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);

        jLabel53.setBackground(new java.awt.Color(204, 204, 204));
        jLabel53.setForeground(new java.awt.Color(51, 51, 51));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("400004");
        jLabel53.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel53.setOpaque(true);
        jLabel53.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel53);

        jLabel52.setBackground(new java.awt.Color(204, 204, 204));
        jLabel52.setForeground(new java.awt.Color(51, 51, 51));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("2022-10-16");
        jLabel52.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel52.setOpaque(true);
        jLabel52.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel52);

        jLabel51.setBackground(new java.awt.Color(204, 204, 204));
        jLabel51.setForeground(new java.awt.Color(51, 51, 51));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("2022-10-31");
        jLabel51.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel51.setOpaque(true);
        jLabel51.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel51);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("View");
        jLabel7.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setForeground(new java.awt.Color(51, 51, 51));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("400005");
        jLabel56.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel56.setOpaque(true);
        jLabel56.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel56);

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setForeground(new java.awt.Color(51, 51, 51));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("2022-11-01");
        jLabel54.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel54.setOpaque(true);
        jLabel54.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel54);

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setForeground(new java.awt.Color(51, 51, 51));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("2022-11-15");
        jLabel57.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel57.setOpaque(true);
        jLabel57.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel57);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("View");
        jLabel8.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);

        jLabel60.setBackground(new java.awt.Color(204, 204, 204));
        jLabel60.setForeground(new java.awt.Color(51, 51, 51));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("400006");
        jLabel60.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel60.setOpaque(true);
        jLabel60.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel60);

        jLabel59.setBackground(new java.awt.Color(204, 204, 204));
        jLabel59.setForeground(new java.awt.Color(51, 51, 51));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("2022-11-16");
        jLabel59.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel59.setOpaque(true);
        jLabel59.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel59);

        jLabel58.setBackground(new java.awt.Color(204, 204, 204));
        jLabel58.setForeground(new java.awt.Color(51, 51, 51));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("2022-11-30");
        jLabel58.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel58.setOpaque(true);
        jLabel58.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.add(jLabel58);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("View");
        jLabel9.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(5, 4));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PayPeriod ID");
        jLabel13.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel13.setOpaque(true);
        jLabel13.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel13);

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Start Date");
        jLabel18.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel18.setOpaque(true);
        jLabel18.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel18);

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("End Date");
        jLabel19.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel19.setOpaque(true);
        jLabel19.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel19);

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Action");
        jLabel10.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel10);

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setForeground(new java.awt.Color(51, 51, 51));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("500001");
        jLabel55.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel55.setOpaque(true);
        jLabel55.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel55);

        jLabel66.setBackground(new java.awt.Color(255, 255, 255));
        jLabel66.setForeground(new java.awt.Color(51, 51, 51));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("2022-09-01");
        jLabel66.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel66.setOpaque(true);
        jLabel66.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel66);

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setForeground(new java.awt.Color(51, 51, 51));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("2022-09-30");
        jLabel67.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel67.setOpaque(true);
        jLabel67.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel67);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("View");
        jLabel11.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel11);

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("500002");
        jLabel35.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel35.setOpaque(true);
        jLabel35.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel35);

        jLabel65.setBackground(new java.awt.Color(204, 204, 204));
        jLabel65.setForeground(new java.awt.Color(51, 51, 51));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("2022-10-01");
        jLabel65.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel65.setOpaque(true);
        jLabel65.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel65);

        jLabel68.setBackground(new java.awt.Color(204, 204, 204));
        jLabel68.setForeground(new java.awt.Color(51, 51, 51));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("2022-10-30");
        jLabel68.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel68.setOpaque(true);
        jLabel68.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel68);

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("View");
        jLabel14.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14);

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setForeground(new java.awt.Color(51, 51, 51));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("500003");
        jLabel61.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel61.setOpaque(true);
        jLabel61.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel61);

        jLabel64.setBackground(new java.awt.Color(255, 255, 255));
        jLabel64.setForeground(new java.awt.Color(51, 51, 51));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("2022-11-01");
        jLabel64.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel64.setOpaque(true);
        jLabel64.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel64);

        jLabel69.setBackground(new java.awt.Color(255, 255, 255));
        jLabel69.setForeground(new java.awt.Color(51, 51, 51));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("2022-11-30");
        jLabel69.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel69.setOpaque(true);
        jLabel69.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel69);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("View");
        jLabel15.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel15.setOpaque(true);
        jLabel15.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15);

        jLabel62.setBackground(new java.awt.Color(204, 204, 204));
        jLabel62.setForeground(new java.awt.Color(51, 51, 51));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("500004");
        jLabel62.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel62.setOpaque(true);
        jLabel62.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel62);

        jLabel63.setBackground(new java.awt.Color(204, 204, 204));
        jLabel63.setForeground(new java.awt.Color(51, 51, 51));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("2022-12-01");
        jLabel63.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel63.setOpaque(true);
        jLabel63.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel63);

        jLabel70.setBackground(new java.awt.Color(204, 204, 204));
        jLabel70.setForeground(new java.awt.Color(51, 51, 51));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("2022-12-31");
        jLabel70.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel70.setOpaque(true);
        jLabel70.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel3.add(jLabel70);

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("View");
        jLabel20.setMinimumSize(new java.awt.Dimension(0, 28));
        jLabel20.setOpaque(true);
        jLabel20.setPreferredSize(new java.awt.Dimension(0, 28));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void displayPayslipDetails(String payslipNo, PayslipReports payslipr) {
        dbManager = new DatabaseManager();
        con = dbManager.getConnection();

        try {
            String query = "SELECT PayslipNo, EmployeeID, Name, Position_Department, TotalAllowance, TotalDeduction, Netpay " +
                           "FROM payslip_view " +
                           "WHERE PayslipNo = ? " +
                           "GROUP BY EmployeeID, PayslipNo";
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setString(1, payslipNo);

            // Execute the query
            try (ResultSet resultSet = pstmt.executeQuery()) {
                DefaultTableModel tableModel = (DefaultTableModel) payslipr.getPayrollreportstbl().getModel();

                // Clear existing data
                tableModel.setRowCount(0);

                // Get column names
                if (tableModel.getColumnCount() == 0) {
                    int columnCount = resultSet.getMetaData().getColumnCount();
                    Vector<String> columnNames = new Vector<>();
                    for (int i = 1; i <= columnCount; i++) {
                        columnNames.add(resultSet.getMetaData().getColumnName(i));
                    }
                    tableModel.setColumnIdentifiers(columnNames);
                }

                // Get rows
                Vector<Vector<Object>> data = new Vector<>();
                while (resultSet.next()) {
                    Vector<Object> row = new Vector<>();
                    row.add(resultSet.getString("PayslipNo"));
                    row.add(resultSet.getString("EmployeeID"));
                    row.add(resultSet.getString("Name"));
                    row.add(resultSet.getString("Position_Department"));
                    row.add(resultSet.getString("TotalAllowance"));
                    row.add(resultSet.getString("TotalDeduction"));
                    row.add(resultSet.getString("Netpay"));
                    data.add(row);
                }

                // Add rows to the table model
                for (Vector<Object> rowData : data) {
                    tableModel.addRow(rowData.toArray());
                }

                payslipr.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // Close connection
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }// Method to retrieve and display payslip details
    
    
    public void displayMonthlyDetails(String monthlyID, MonthlySummaryReport mreport) {
        dbManager = new DatabaseManager();
        con = dbManager.getConnection();

        try {
            String query = "SELECT MonthlyPeriodID, EmployeeID, FullName, Position, Department, GrossIncome, SSS_Contribution, Philhealth_Contribution, PagIbig_Contribution, Withholding_Tax, NetPay " +
                           "FROM monhtlyperiod_view " +
                           "WHERE MonthlyPeriodID = ? " +
                           "GROUP BY EmployeeID, MonthlyPeriodID";
            
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setString(1, monthlyID);

            // Execute the query
            try (ResultSet resultSet = pstmt.executeQuery()) {
                DefaultTableModel tableModel = (DefaultTableModel) mreport.getMonthlySummarytbl().getModel();

                // Clear existing data
                tableModel.setRowCount(0);

                // Get column names
                if (tableModel.getColumnCount() == 0) {
                    int columnCount = resultSet.getMetaData().getColumnCount();
                    Vector<String> columnNames = new Vector<>();
                    for (int i = 1; i <= columnCount; i++) {
                        columnNames.add(resultSet.getMetaData().getColumnName(i));
                    }
                    tableModel.setColumnIdentifiers(columnNames);
                }

                // Get rows
                Vector<Vector<Object>> data = new Vector<>();
                while (resultSet.next()) {
                    Vector<Object> row = new Vector<>();
                    row.add(resultSet.getString("MonthlyPeriodID"));
                    row.add(resultSet.getString("EmployeeID"));
                    row.add(resultSet.getString("FullName"));
                    row.add(resultSet.getString("Position"));
                    row.add(resultSet.getString("Department"));
                    row.add(resultSet.getString("GrossIncome"));
                    row.add(resultSet.getString("SSS_Contribution"));
                    row.add(resultSet.getString("Philhealth_Contribution"));
                    row.add(resultSet.getString("PagIbig_Contribution"));
                    row.add(resultSet.getString("Withholding_Tax"));
                    row.add(resultSet.getString("Netpay"));
                    data.add(row);
                }

                // Add rows to the table model
                for (Vector<Object> rowData : data) {
                    tableModel.addRow(rowData.toArray());
                }

                mreport.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // Close connection
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
    
   // Method to populate JLabels with data from monthlytotal_view
    public void populateMonthlyTotal(String monthlyPeriodID, MonthlySummaryReport report) {
        dbManager = new DatabaseManager();
        con = dbManager.getConnection();

        String query = "SELECT TotalGrossIncome, TotalSSS_Contribution, TotalPhilhealth_Contribution, TotalPagIbig_Contribution, TotalWithholding_Tax, TotalNetPay " +
                       "FROM monthlytotal_view WHERE MonthlyPeriodID = ?";

        try (PreparedStatement pstmt = con.prepareStatement(query)) {
            pstmt.setString(1, monthlyPeriodID);

            try (ResultSet resultSet = pstmt.executeQuery()) {
                if (resultSet.next()) {
                    double totalGrossIncome = resultSet.getDouble("TotalGrossIncome"); // Retrieve as double
                    double phealth = resultSet.getDouble("TotalPhilhealth_Contribution"); 
                    double tax = resultSet.getDouble("TotalWithholding_Tax"); 
                    
                    report.getGrossSalary().setText("Php" +" "+ String.format("%.2f", totalGrossIncome));
                    report.getSss().setText("Php" +" "+resultSet.getString("TotalSSS_Contribution"));
                    report.getPhilhealth().setText("Php" +" "+ String.format("%.2f", phealth));
                    report.getPagibig().setText("Php" +" "+ resultSet.getString("TotalPagIbig_Contribution"));
                    report.getTax().setText("Php" + " "+String.format("%.2f", tax));
                    report.getNetpay().setText("Php" + " "+resultSet.getString("TotalNetPay"));
                } else {
                    // Handle the case where no data is found
                    report.getGrossSalary().setText("N/A");
                    report.getSss().setText("N/A");
                    report.getPhilhealth().setText("N/A");
                    report.getPagibig().setText("N/A");
                    report.getTax().setText("N/A");
                    report.getNetpay().setText("N/A");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PayrollReports.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
    
    
    
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    String payslipNo = "400001";
    PayslipReports payslipr = new PayslipReports();
    displayPayslipDetails(payslipNo, payslipr);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
  String payslipNo = "400002";
  PayslipReports payslipr = new PayslipReports();
  displayPayslipDetails(payslipNo, payslipr);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
  String payslipNo = "400003";
PayslipReports payslipr = new PayslipReports();
displayPayslipDetails(payslipNo, payslipr);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
  String payslipNo = "400004";
PayslipReports payslipr = new PayslipReports();
displayPayslipDetails(payslipNo, payslipr);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
  String payslipNo = "400005";
 PayslipReports payslipr = new PayslipReports();
 displayPayslipDetails(payslipNo, payslipr);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
  String payslipNo = "400006";
PayslipReports payslipr = new PayslipReports();
displayPayslipDetails(payslipNo, payslipr);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    
    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        try{
            //Class.forName("com.mysql.cj.jdbc.Driver");
            dbManager = new DatabaseManager();
            con = dbManager.getConnection();
            int month = 500001;
            
            // Get the application's directory
                File currentDir = new File(System.getProperty("user.dir"));
                
                String reportPath = new File(currentDir, "reports/payroll_summary.jrxml").getAbsolutePath();
                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                
                // Set the path to the image
                String imagePath = new File(currentDir, "reports/mph_logo.png").getAbsolutePath();
                
                Map<String, Object> parameters = new HashMap<>();                
                parameters.put("MonthlyPeriodID", month);
                parameters.put("IMAGE_PATH", imagePath); // Pass the image path as a parameter
                
                JasperPrint jp = JasperFillManager.fillReport(jr, parameters, con);
                JasperViewer.viewReport(jp, false);
                
//            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
         try{
            //Class.forName("com.mysql.cj.jdbc.Driver");
            dbManager = new DatabaseManager();
            con = dbManager.getConnection();
            int month = 500002;
            
            // Get the application's directory
                File currentDir = new File(System.getProperty("user.dir"));
                
                String reportPath = new File(currentDir, "reports/payroll_summary.jrxml").getAbsolutePath();
                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                
                // Set the path to the image
                String imagePath = new File(currentDir, "reports/mph_logo.png").getAbsolutePath();
                
                Map<String, Object> parameters = new HashMap<>();                
                parameters.put("MonthlyPeriodID", month);
                parameters.put("IMAGE_PATH", imagePath); // Pass the image path as a parameter
                
                JasperPrint jp = JasperFillManager.fillReport(jr, parameters, con);
                JasperViewer.viewReport(jp, false);
                
//            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
       try{
            //Class.forName("com.mysql.cj.jdbc.Driver");
            dbManager = new DatabaseManager();
            con = dbManager.getConnection();
            int month = 500003;
            
            // Get the application's directory
                File currentDir = new File(System.getProperty("user.dir"));
                
                String reportPath = new File(currentDir, "reports/payroll_summary.jrxml").getAbsolutePath();
                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                
                // Set the path to the image
                String imagePath = new File(currentDir, "reports/mph_logo.png").getAbsolutePath();
                
                Map<String, Object> parameters = new HashMap<>();                
                parameters.put("MonthlyPeriodID", month);
                parameters.put("IMAGE_PATH", imagePath); // Pass the image path as a parameter
                
                JasperPrint jp = JasperFillManager.fillReport(jr, parameters, con);
                JasperViewer.viewReport(jp, false);
                
//            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        try{
            //Class.forName("com.mysql.cj.jdbc.Driver");
            dbManager = new DatabaseManager();
            con = dbManager.getConnection();
            int month = 500004;
            
            // Get the application's directory
                File currentDir = new File(System.getProperty("user.dir"));
                
                String reportPath = new File(currentDir, "reports/payroll_summary.jrxml").getAbsolutePath();
                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                
                // Set the path to the image
                String imagePath = new File(currentDir, "reports/mph_logo.png").getAbsolutePath();
                
                Map<String, Object> parameters = new HashMap<>();                
                parameters.put("MonthlyPeriodID", month);
                parameters.put("IMAGE_PATH", imagePath); // Pass the image path as a parameter
                
                JasperPrint jp = JasperFillManager.fillReport(jr, parameters, con);
                JasperViewer.viewReport(jp, false);
                
//            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
